#!/usr/bin/python

import sys, requests
from xml.etree import ElementTree
import html
import config

URL="http://localhost:8080/wx/fetch"
PHONE="+19713364571"


body = ' '.join(sys.argv[1:])
if not len(body):
    body = "help me"

args = {'Body': html.escape(body), 'From': PHONE}

auth = requests.auth.HTTPBasicAuth(
    config.BASICAUTH_USER,config.BASICAUTH_PASS)

r = requests.get(
    URL,
    params = args,
    auth = auth
)
tree = ElementTree.fromstring(r.content)
print ( html.unescape(tree.find('Message').text) )
